

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python src/main.py
    container_name: movielens-backend

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm start
    container_name: movielens-frontend
    stdin_open: true
    tty: true
